language: python

python:
  - "3.8"
  - "3.7"
  - "3.6"
  - "3.5"
  - "3.4"

env:
  - DJANGO="django==1.11.9"
  - DJANGO="django==1.10.8"
  - DJANGO="django==1.9.13"
  - DJANGO="django==1.8.18"
  - DJANGO="django==2.0.1"

install:
  - pip install $DJANGO
  - pip install flake8
  - pip install coveralls

before_script:
   flake8 .

script: coverage run --source=menu_generator manage.py test

after_success:
  coveralls